### ISSUE TITLE
Update JOGL

### ISSUE THREAD

**Issue by michaelzangl** [kendzi/josm-jogl#1]
I want to use this plugin to provide JOGL for the OpenGL map view. Is it possible to update the contained JOGL libraries to 2.3.1?

There are a few changes required when switching (some method names changed)

**Comment by kendzi** [comment]
Hello, I will update it as soon as possible. Should be ready till end of week.

Btw. If you are loading JOGL library's you should use that plugin because it only provide jars and adds them to class-path. You can easily add it as dependency to your plugin. There is no reason to provide the same jars in two different plugins because it will cause problems in future.

**Comment by kendzi** [comment]
Oh, crap, they changed package names :/

**Comment by michaelzangl** [comment]
Yes, and they changed a few method names (something like getDrawableWidth -> getSurfaceWidth).

If it is a problem to update this plugin (since other plugins might also suffer from this), I can try downgrading JOGL for my project. My problem is that I am using a third party library (GLG2D) that is based on the current version of JOGL.

As soon as the version is the same, I will simply use this plugin.

**Comment by kendzi** [comment]
Never downgrade, it is only postponing problems for future. I will upgrade it as soon as possible.

**Comment by kendzi** [comment]
Oh, I forgot, one fork of kendzi3d exists called "Kendzi3D_Improved_by_Andrei": https://github.com/andreimaneasa/kendzi3d
I had write email to the author.

**Comment by kendzi** [comment]
Done. I have released new version with new jogl.
